#!/bin/python
# Launcher script for disrichie
import os
import sys
from sys import exit

cwd = os.path.dirname(os.path.abspath(__file__))
script_dir: str = f"{cwd}/scripts"
script_main: str = f"{script_dir}/main.py"

class PyInteractiveError(Exception):
	def __init__(self):
		super().__init__('Do not run from an interactive Python instance!')

class DisrichieMainError(Exception):
	def __init__(self):
		super().__init__('Initialization error')

def handle_launcher_args():
	if '--tracebacks' not in sys.argv: sys.tracebacklimit = 0
	if '--cache' not in sys.argv: sys.dont_write_bytecode = True
	if '-v' in sys.argv or '--version' in sys.argv:
		print('version 1.0.2')
		exit()
	if '-h' in sys.argv or '--help' in sys.argv:
		print('disrichie - A simple program to display custom Rich Presence on Discord!')
		print('\nArguments:')
		print('	-h / --help : Display help information')
		print('	-v / --version : Print program version')
		print('	-p / --profile : Specify Rich Presence profile')
		print('	-i / --id : Specify Client ID for Rich Presence')
		print('	--wait : Do not put Disrichie into background and wait')
		print('\nLauncher arguments:')
		print('	--cache : Enable caching for this session')
		print('	--tracebacks : Print not only the error but from where it was fired')
		print('\nYou can view more information here: NULL')
		exit()

def check_interactive():
	try:
		__file__
	except NameError:
		raise PyInteractiveError

def launch():
	try:
		from main import Disrichie
		instance = Disrichie(sys.argv[1:])
		instance.start()
	except ModuleNotFoundError:
		raise DisrichieMainError()

# Main code
check_interactive()
handle_launcher_args()
sys.path.insert(0, script_dir)
launch()